name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/former-frontend
    steps:
      - uses: actions/checkout@v6
      - name: Log In to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          IMAGE_NAME_LOWERCASE=${IMAGE_NAME,,}
          docker build -t ${IMAGE_NAME_LOWERCASE}:latest .
      - name: Push
        run: |
          IMAGE_NAME_LOWERCASE=${IMAGE_NAME,,}
          docker push ${IMAGE_NAME_LOWERCASE}:latest
